name: windows

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        build-type: [ Release, RelWithDebInfo ]
        platform: [ x64, Win32 ]
        compiler: [ v143, ClangCL ]
        generator: [ "Visual Studio 17 2022" ]
        lib-type: [ { name: Static, cmake-shared-flag: "OFF" }, { name: Shared, cmake-shared-flag: "ON" } ]
        exclude:
          - platform: Win32
            compiler: ClangCL
          - platform: Win32
            build-type: Release

    defaults:
      run:
        working-directory: ${{ github.workspace }}/build

    name: ${{ matrix.compiler }}-${{ matrix.platform }}, ${{ matrix.build-type }}, ${{ matrix.lib-type.name }}


    steps:
    - name: checkout-repo
      uses: actions/checkout@v3

    #- name: setup-compiler
    #  run: choco install -y --allow-downgrade ${{ matrix.compiler.pkgs }}

    - name: setup-catch
      env:
        CMAKE_GENERATOR: ${{ matrix.generator }}
        CMAKE_GENERATOR_TOOLSET: ${{ matrix.compiler }}
        CMAKE_GENERATOR_PLATFORM: ${{ matrix.platform }}
      run: bash ./install_catch.sh

    - name: setup-build
      env:
        CMAKE_GENERATOR: ${{ matrix.generator }}
        CMAKE_GENERATOR_TOOLSET: ${{ matrix.compiler }}
        CMAKE_GENERATOR_PLATFORM: ${{ matrix.platform }}
      run: cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} -DBUILD_SHARED_LIBS=${{ matrix.lib-type.cmake-shared-flag }}

    - name: build
      run: cmake --build . --parallel --config ${{ matrix.build-type }}
    
    - name: run-tests
      run: ctest --output-on-failure --schedule-random

    - name: install
      run: cmake --install . --config ${{ matrix.build-type }}
