name: windows

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        build-type: [ Release, RelWithDebInfo, Debug ]
        platform: [ x64, Win32 ]
        generator: [ "Visual Studio 17 2022" ]
        compiler: [ 
            { name: msvc, toolset: v143 }, 
            { name: clang, toolset: ClangCL }
        ]
        build-shared: [ "ON", "OFF" ]
        exclude:
          - platform: Win32
            build-type: Release
          - platform: Win32
            build-type: Debug
          - platform: Win32
            build-shared: "OFF"

    defaults:
      run:
        working-directory: ${{ github.workspace }}/build

    name: ${{ matrix.compiler.name }}-${{ matrix.platform }}, ${{ matrix.build-type }}, Shared=${{ matrix.build-shared }}


    steps:
    - name: checkout-repo
      uses: actions/checkout@v4

    - name: setup-catch
      env:
        CMAKE_GENERATOR: ${{ matrix.generator }}
        CMAKE_GENERATOR_TOOLSET: ${{ matrix.compiler.toolset }}
        CMAKE_GENERATOR_PLATFORM: ${{ matrix.platform }}
      run: bash ../tools/install_catch.sh ${{ matrix.build-type }}

    - name: setup-build
      env:
        CMAKE_GENERATOR: ${{ matrix.generator }}
        CMAKE_GENERATOR_TOOLSET: ${{ matrix.compiler.toolset }}
        CMAKE_GENERATOR_PLATFORM: ${{ matrix.platform }}
      run: cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} -DBUILD_SHARED_LIBS=${{ matrix.build-shared }} -DGAPP_USE_WERROR=ON -DGAPP_USE_LTO=ON

    - name: build
      run: cmake --build . --parallel --config ${{ matrix.build-type }}
    
    - name: run-tests
      run: ctest --output-on-failure --schedule-random

    - name: install
      run: cmake --install . --config ${{ matrix.build-type }}

    - name: run-reproducibility-test
      run: ${{ matrix.build-type }}/reproducibility_test | tee results-${{ matrix.compiler.name }}-${{ matrix.build-type }}-${{ matrix.platform }}-shared${{ matrix.build-shared }}.txt

    - uses: actions/upload-artifact@v4
      with:
        name: results-${{ matrix.compiler.name }}-${{ matrix.build-type }}-${{ matrix.platform }}-shared${{ matrix.build-shared }}
        path: ${{ github.workspace }}/build/results-${{ matrix.compiler.name }}-${{ matrix.build-type }}-${{ matrix.platform }}-shared${{ matrix.build-shared }}.txt


  compare:
    needs: build
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: results*
          merge-multiple: true

      - name: compare-results
        run: diff --unified=0 --to-file results*
